dbus_interfaces = [
  'io.github.scarecrow_de.Shell.Extensions.xml',
  'io.github.scarecrow_de.Shell.Introspect.xml',
  'io.github.scarecrow_de.Shell.PadOsd.xml',
  'io.github.scarecrow_de.Shell.Screencast.xml',
  'io.github.scarecrow_de.Shell.Screenshot.xml',
  'io.github.scarecrow_de.ShellSearchProvider.xml',
  'io.github.scarecrow_de.ShellSearchProvider2.xml'
]
install_data(dbus_interfaces, install_dir: ifacedir)
