dbus_interfaces = [
  'io.github.scarecrow-de.Shell.Extensions.xml',
  'io.github.scarecrow-de.Shell.Introspect.xml',
  'io.github.scarecrow-de.Shell.PadOsd.xml',
  'io.github.scarecrow-de.Shell.Screencast.xml',
  'io.github.scarecrow-de.Shell.Screenshot.xml',
  'io.github.scarecrow-de.ShellSearchProvider.xml',
  'io.github.scarecrow-de.ShellSearchProvider2.xml'
]
install_data(dbus_interfaces, install_dir: ifacedir)
